import React from "react";

const CopySvg = () => {
  return (
    <svg
      className="copy-svg"
      version="1.1"
      width="36"
      height="40"
      xmlns="http://www.w3.org/2000/svg"
      shape-rendering="crispEdges"
      viewBox="0 0 36 40"
    >
      <rect x="0" y="0" width="1" height="1" className="path-fill" />
      <rect x="1" y="0" width="1" height="1" className="path-fill" />
      <rect x="2" y="0" width="1" height="1" className="path-fill" />
      <rect x="3" y="0" width="1" height="1" className="path-fill" />
      <rect x="4" y="0" width="1" height="1" className="path-fill" />
      <rect x="5" y="0" width="1" height="1" className="path-fill" />
      <rect x="6" y="0" width="1" height="1" className="path-fill" />
      <rect x="7" y="0" width="1" height="1" className="path-fill" />
      <rect x="8" y="0" width="1" height="1" className="path-fill" />
      <rect x="9" y="0" width="1" height="1" className="path-fill" />
      <rect x="10" y="0" width="1" height="1" className="path-fill" />
      <rect x="11" y="0" width="1" height="1" className="path-fill" />
      <rect x="12" y="0" width="1" height="1" className="path-fill" />
      <rect x="13" y="0" width="1" height="1" className="path-fill" />
      <rect x="14" y="0" width="1" height="1" className="path-fill" />
      <rect x="15" y="0" width="1" height="1" className="path-fill" />
      <rect x="16" y="0" width="1" height="1" className="path-fill" />
      <rect x="17" y="0" width="1" height="1" className="path-fill" />
      <rect x="18" y="0" width="1" height="1" className="path-fill" />
      <rect x="19" y="0" width="1" height="1" className="path-fill" />
      <rect x="20" y="0" width="1" height="1" className="path-fill" />
      <rect x="21" y="0" width="1" height="1" className="path-fill" />
      <rect x="22" y="0" width="1" height="1" className="path-fill" />
      <rect x="23" y="0" width="1" height="1" className="path-fill" />
      <rect x="0" y="1" width="1" height="1" className="path-fill" />
      <rect x="1" y="1" width="1" height="1" className="path-fill" />
      <rect x="2" y="1" width="1" height="1" className="path-fill" />
      <rect x="3" y="1" width="1" height="1" className="path-fill" />
      <rect x="4" y="1" width="1" height="1" className="path-fill" />
      <rect x="5" y="1" width="1" height="1" className="path-fill" />
      <rect x="6" y="1" width="1" height="1" className="path-fill" />
      <rect x="7" y="1" width="1" height="1" className="path-fill" />
      <rect x="8" y="1" width="1" height="1" className="path-fill" />
      <rect x="9" y="1" width="1" height="1" className="path-fill" />
      <rect x="10" y="1" width="1" height="1" className="path-fill" />
      <rect x="11" y="1" width="1" height="1" className="path-fill" />
      <rect x="12" y="1" width="1" height="1" className="path-fill" />
      <rect x="13" y="1" width="1" height="1" className="path-fill" />
      <rect x="14" y="1" width="1" height="1" className="path-fill" />
      <rect x="15" y="1" width="1" height="1" className="path-fill" />
      <rect x="16" y="1" width="1" height="1" className="path-fill" />
      <rect x="17" y="1" width="1" height="1" className="path-fill" />
      <rect x="18" y="1" width="1" height="1" className="path-fill" />
      <rect x="19" y="1" width="1" height="1" className="path-fill" />
      <rect x="20" y="1" width="1" height="1" className="path-fill" />
      <rect x="21" y="1" width="1" height="1" className="path-fill" />
      <rect x="22" y="1" width="1" height="1" className="path-fill" />
      <rect x="23" y="1" width="1" height="1" className="path-fill" />
      <rect x="0" y="2" width="1" height="1" className="path-fill" />
      <rect x="1" y="2" width="1" height="1" className="path-fill" />
      <rect x="2" y="2" width="1" height="1" className="path-fill" />
      <rect x="3" y="2" width="1" height="1" className="path-fill" />
      <rect x="4" y="2" width="1" height="1" className="path-fill" />
      <rect x="5" y="2" width="1" height="1" className="path-fill" />
      <rect x="6" y="2" width="1" height="1" className="path-fill" />
      <rect x="7" y="2" width="1" height="1" className="path-fill" />
      <rect x="8" y="2" width="1" height="1" className="path-fill" />
      <rect x="9" y="2" width="1" height="1" className="path-fill" />
      <rect x="10" y="2" width="1" height="1" className="path-fill" />
      <rect x="11" y="2" width="1" height="1" className="path-fill" />
      <rect x="12" y="2" width="1" height="1" className="path-fill" />
      <rect x="13" y="2" width="1" height="1" className="path-fill" />
      <rect x="14" y="2" width="1" height="1" className="path-fill" />
      <rect x="15" y="2" width="1" height="1" className="path-fill" />
      <rect x="16" y="2" width="1" height="1" className="path-fill" />
      <rect x="17" y="2" width="1" height="1" className="path-fill" />
      <rect x="18" y="2" width="1" height="1" className="path-fill" />
      <rect x="19" y="2" width="1" height="1" className="path-fill" />
      <rect x="20" y="2" width="1" height="1" className="path-fill" />
      <rect x="21" y="2" width="1" height="1" className="path-fill" />
      <rect x="22" y="2" width="1" height="1" className="path-fill" />
      <rect x="23" y="2" width="1" height="1" className="path-fill" />
      <rect x="0" y="3" width="1" height="1" className="path-fill" />
      <rect x="1" y="3" width="1" height="1" className="path-fill" />
      <rect x="2" y="3" width="1" height="1" className="path-fill" />
      <rect x="3" y="3" width="1" height="1" className="path-fill" />
      <rect x="4" y="3" width="1" height="1" className="path-fill" />
      <rect x="5" y="3" width="1" height="1" className="path-fill" />
      <rect x="6" y="3" width="1" height="1" className="path-fill" />
      <rect x="7" y="3" width="1" height="1" className="path-fill" />
      <rect x="8" y="3" width="1" height="1" className="path-fill" />
      <rect x="9" y="3" width="1" height="1" className="path-fill" />
      <rect x="10" y="3" width="1" height="1" className="path-fill" />
      <rect x="11" y="3" width="1" height="1" className="path-fill" />
      <rect x="12" y="3" width="1" height="1" className="path-fill" />
      <rect x="13" y="3" width="1" height="1" className="path-fill" />
      <rect x="14" y="3" width="1" height="1" className="path-fill" />
      <rect x="15" y="3" width="1" height="1" className="path-fill" />
      <rect x="16" y="3" width="1" height="1" className="path-fill" />
      <rect x="17" y="3" width="1" height="1" className="path-fill" />
      <rect x="18" y="3" width="1" height="1" className="path-fill" />
      <rect x="19" y="3" width="1" height="1" className="path-fill" />
      <rect x="20" y="3" width="1" height="1" className="path-fill" />
      <rect x="21" y="3" width="1" height="1" className="path-fill" />
      <rect x="22" y="3" width="1" height="1" className="path-fill" />
      <rect x="23" y="3" width="1" height="1" className="path-fill" />
      <rect x="0" y="4" width="1" height="1" className="path-fill" />
      <rect x="1" y="4" width="1" height="1" className="path-fill" />
      <rect x="2" y="4" width="1" height="1" className="path-fill" />
      <rect x="3" y="4" width="1" height="1" className="path-fill" />
      <rect x="20" y="4" width="1" height="1" className="path-fill" />
      <rect x="21" y="4" width="1" height="1" className="path-fill" />
      <rect x="22" y="4" width="1" height="1" className="path-fill" />
      <rect x="23" y="4" width="1" height="1" className="path-fill" />
      <rect x="0" y="5" width="1" height="1" className="path-fill" />
      <rect x="1" y="5" width="1" height="1" className="path-fill" />
      <rect x="2" y="5" width="1" height="1" className="path-fill" />
      <rect x="3" y="5" width="1" height="1" className="path-fill" />
      <rect x="20" y="5" width="1" height="1" className="path-fill" />
      <rect x="21" y="5" width="1" height="1" className="path-fill" />
      <rect x="22" y="5" width="1" height="1" className="path-fill" />
      <rect x="23" y="5" width="1" height="1" className="path-fill" />
      <rect x="0" y="6" width="1" height="1" className="path-fill" />
      <rect x="1" y="6" width="1" height="1" className="path-fill" />
      <rect x="2" y="6" width="1" height="1" className="path-fill" />
      <rect x="3" y="6" width="1" height="1" className="path-fill" />
      <rect x="20" y="6" width="1" height="1" className="path-fill" />
      <rect x="21" y="6" width="1" height="1" className="path-fill" />
      <rect x="22" y="6" width="1" height="1" className="path-fill" />
      <rect x="23" y="6" width="1" height="1" className="path-fill" />
      <rect x="0" y="7" width="1" height="1" className="path-fill" />
      <rect x="1" y="7" width="1" height="1" className="path-fill" />
      <rect x="2" y="7" width="1" height="1" className="path-fill" />
      <rect x="3" y="7" width="1" height="1" className="path-fill" />
      <rect x="20" y="7" width="1" height="1" className="path-fill" />
      <rect x="21" y="7" width="1" height="1" className="path-fill" />
      <rect x="22" y="7" width="1" height="1" className="path-fill" />
      <rect x="23" y="7" width="1" height="1" className="path-fill" />
      <rect x="0" y="8" width="1" height="1" className="path-fill" />
      <rect x="1" y="8" width="1" height="1" className="path-fill" />
      <rect x="2" y="8" width="1" height="1" className="path-fill" />
      <rect x="3" y="8" width="1" height="1" className="path-fill" />
      <rect x="12" y="8" width="1" height="1" className="path-fill" />
      <rect x="13" y="8" width="1" height="1" className="path-fill" />
      <rect x="14" y="8" width="1" height="1" className="path-fill" />
      <rect x="15" y="8" width="1" height="1" className="path-fill" />
      <rect x="16" y="8" width="1" height="1" className="path-fill" />
      <rect x="17" y="8" width="1" height="1" className="path-fill" />
      <rect x="18" y="8" width="1" height="1" className="path-fill" />
      <rect x="19" y="8" width="1" height="1" className="path-fill" />
      <rect x="20" y="8" width="1" height="1" className="path-fill" />
      <rect x="21" y="8" width="1" height="1" className="path-fill" />
      <rect x="22" y="8" width="1" height="1" className="path-fill" />
      <rect x="23" y="8" width="1" height="1" className="path-fill" />
      <rect x="24" y="8" width="1" height="1" className="path-fill" />
      <rect x="25" y="8" width="1" height="1" className="path-fill" />
      <rect x="26" y="8" width="1" height="1" className="path-fill" />
      <rect x="27" y="8" width="1" height="1" className="path-fill" />
      <rect x="0" y="9" width="1" height="1" className="path-fill" />
      <rect x="1" y="9" width="1" height="1" className="path-fill" />
      <rect x="2" y="9" width="1" height="1" className="path-fill" />
      <rect x="3" y="9" width="1" height="1" className="path-fill" />
      <rect x="12" y="9" width="1" height="1" className="path-fill" />
      <rect x="13" y="9" width="1" height="1" className="path-fill" />
      <rect x="14" y="9" width="1" height="1" className="path-fill" />
      <rect x="15" y="9" width="1" height="1" className="path-fill" />
      <rect x="16" y="9" width="1" height="1" className="path-fill" />
      <rect x="17" y="9" width="1" height="1" className="path-fill" />
      <rect x="18" y="9" width="1" height="1" className="path-fill" />
      <rect x="19" y="9" width="1" height="1" className="path-fill" />
      <rect x="20" y="9" width="1" height="1" className="path-fill" />
      <rect x="21" y="9" width="1" height="1" className="path-fill" />
      <rect x="22" y="9" width="1" height="1" className="path-fill" />
      <rect x="23" y="9" width="1" height="1" className="path-fill" />
      <rect x="24" y="9" width="1" height="1" className="path-fill" />
      <rect x="25" y="9" width="1" height="1" className="path-fill" />
      <rect x="26" y="9" width="1" height="1" className="path-fill" />
      <rect x="27" y="9" width="1" height="1" className="path-fill" />
      <rect x="0" y="10" width="1" height="1" className="path-fill" />
      <rect x="1" y="10" width="1" height="1" className="path-fill" />
      <rect x="2" y="10" width="1" height="1" className="path-fill" />
      <rect x="3" y="10" width="1" height="1" className="path-fill" />
      <rect x="12" y="10" width="1" height="1" className="path-fill" />
      <rect x="13" y="10" width="1" height="1" className="path-fill" />
      <rect x="14" y="10" width="1" height="1" className="path-fill" />
      <rect x="15" y="10" width="1" height="1" className="path-fill" />
      <rect x="16" y="10" width="1" height="1" className="path-fill" />
      <rect x="17" y="10" width="1" height="1" className="path-fill" />
      <rect x="18" y="10" width="1" height="1" className="path-fill" />
      <rect x="19" y="10" width="1" height="1" className="path-fill" />
      <rect x="20" y="10" width="1" height="1" className="path-fill" />
      <rect x="21" y="10" width="1" height="1" className="path-fill" />
      <rect x="22" y="10" width="1" height="1" className="path-fill" />
      <rect x="23" y="10" width="1" height="1" className="path-fill" />
      <rect x="24" y="10" width="1" height="1" className="path-fill" />
      <rect x="25" y="10" width="1" height="1" className="path-fill" />
      <rect x="26" y="10" width="1" height="1" className="path-fill" />
      <rect x="27" y="10" width="1" height="1" className="path-fill" />
      <rect x="0" y="11" width="1" height="1" className="path-fill" />
      <rect x="1" y="11" width="1" height="1" className="path-fill" />
      <rect x="2" y="11" width="1" height="1" className="path-fill" />
      <rect x="3" y="11" width="1" height="1" className="path-fill" />
      <rect x="12" y="11" width="1" height="1" className="path-fill" />
      <rect x="13" y="11" width="1" height="1" className="path-fill" />
      <rect x="14" y="11" width="1" height="1" className="path-fill" />
      <rect x="15" y="11" width="1" height="1" className="path-fill" />
      <rect x="16" y="11" width="1" height="1" className="path-fill" />
      <rect x="17" y="11" width="1" height="1" className="path-fill" />
      <rect x="18" y="11" width="1" height="1" className="path-fill" />
      <rect x="19" y="11" width="1" height="1" className="path-fill" />
      <rect x="20" y="11" width="1" height="1" className="path-fill" />
      <rect x="21" y="11" width="1" height="1" className="path-fill" />
      <rect x="22" y="11" width="1" height="1" className="path-fill" />
      <rect x="23" y="11" width="1" height="1" className="path-fill" />
      <rect x="24" y="11" width="1" height="1" className="path-fill" />
      <rect x="25" y="11" width="1" height="1" className="path-fill" />
      <rect x="26" y="11" width="1" height="1" className="path-fill" />
      <rect x="27" y="11" width="1" height="1" className="path-fill" />
      <rect x="0" y="12" width="1" height="1" className="path-fill" />
      <rect x="1" y="12" width="1" height="1" className="path-fill" />
      <rect x="2" y="12" width="1" height="1" className="path-fill" />
      <rect x="3" y="12" width="1" height="1" className="path-fill" />
      <rect x="12" y="12" width="1" height="1" className="path-fill" />
      <rect x="13" y="12" width="1" height="1" className="path-fill" />
      <rect x="14" y="12" width="1" height="1" className="path-fill" />
      <rect x="15" y="12" width="1" height="1" className="path-fill" />
      <rect x="28" y="12" width="1" height="1" className="path-fill" />
      <rect x="29" y="12" width="1" height="1" className="path-fill" />
      <rect x="30" y="12" width="1" height="1" className="path-fill" />
      <rect x="31" y="12" width="1" height="1" className="path-fill" />
      <rect x="0" y="13" width="1" height="1" className="path-fill" />
      <rect x="1" y="13" width="1" height="1" className="path-fill" />
      <rect x="2" y="13" width="1" height="1" className="path-fill" />
      <rect x="3" y="13" width="1" height="1" className="path-fill" />
      <rect x="12" y="13" width="1" height="1" className="path-fill" />
      <rect x="13" y="13" width="1" height="1" className="path-fill" />
      <rect x="14" y="13" width="1" height="1" className="path-fill" />
      <rect x="15" y="13" width="1" height="1" className="path-fill" />
      <rect x="28" y="13" width="1" height="1" className="path-fill" />
      <rect x="29" y="13" width="1" height="1" className="path-fill" />
      <rect x="30" y="13" width="1" height="1" className="path-fill" />
      <rect x="31" y="13" width="1" height="1" className="path-fill" />
      <rect x="0" y="14" width="1" height="1" className="path-fill" />
      <rect x="1" y="14" width="1" height="1" className="path-fill" />
      <rect x="2" y="14" width="1" height="1" className="path-fill" />
      <rect x="3" y="14" width="1" height="1" className="path-fill" />
      <rect x="12" y="14" width="1" height="1" className="path-fill" />
      <rect x="13" y="14" width="1" height="1" className="path-fill" />
      <rect x="14" y="14" width="1" height="1" className="path-fill" />
      <rect x="15" y="14" width="1" height="1" className="path-fill" />
      <rect x="28" y="14" width="1" height="1" className="path-fill" />
      <rect x="29" y="14" width="1" height="1" className="path-fill" />
      <rect x="30" y="14" width="1" height="1" className="path-fill" />
      <rect x="31" y="14" width="1" height="1" className="path-fill" />
      <rect x="0" y="15" width="1" height="1" className="path-fill" />
      <rect x="1" y="15" width="1" height="1" className="path-fill" />
      <rect x="2" y="15" width="1" height="1" className="path-fill" />
      <rect x="3" y="15" width="1" height="1" className="path-fill" />
      <rect x="12" y="15" width="1" height="1" className="path-fill" />
      <rect x="13" y="15" width="1" height="1" className="path-fill" />
      <rect x="14" y="15" width="1" height="1" className="path-fill" />
      <rect x="15" y="15" width="1" height="1" className="path-fill" />
      <rect x="28" y="15" width="1" height="1" className="path-fill" />
      <rect x="29" y="15" width="1" height="1" className="path-fill" />
      <rect x="30" y="15" width="1" height="1" className="path-fill" />
      <rect x="31" y="15" width="1" height="1" className="path-fill" />
      <rect x="0" y="16" width="1" height="1" className="path-fill" />
      <rect x="1" y="16" width="1" height="1" className="path-fill" />
      <rect x="2" y="16" width="1" height="1" className="path-fill" />
      <rect x="3" y="16" width="1" height="1" className="path-fill" />
      <rect x="12" y="16" width="1" height="1" className="path-fill" />
      <rect x="13" y="16" width="1" height="1" className="path-fill" />
      <rect x="14" y="16" width="1" height="1" className="path-fill" />
      <rect x="15" y="16" width="1" height="1" className="path-fill" />
      <rect x="32" y="16" width="1" height="1" className="path-fill" />
      <rect x="33" y="16" width="1" height="1" className="path-fill" />
      <rect x="34" y="16" width="1" height="1" className="path-fill" />
      <rect x="35" y="16" width="1" height="1" className="path-fill" />
      <rect x="0" y="17" width="1" height="1" className="path-fill" />
      <rect x="1" y="17" width="1" height="1" className="path-fill" />
      <rect x="2" y="17" width="1" height="1" className="path-fill" />
      <rect x="3" y="17" width="1" height="1" className="path-fill" />
      <rect x="12" y="17" width="1" height="1" className="path-fill" />
      <rect x="13" y="17" width="1" height="1" className="path-fill" />
      <rect x="14" y="17" width="1" height="1" className="path-fill" />
      <rect x="15" y="17" width="1" height="1" className="path-fill" />
      <rect x="32" y="17" width="1" height="1" className="path-fill" />
      <rect x="33" y="17" width="1" height="1" className="path-fill" />
      <rect x="34" y="17" width="1" height="1" className="path-fill" />
      <rect x="35" y="17" width="1" height="1" className="path-fill" />
      <rect x="0" y="18" width="1" height="1" className="path-fill" />
      <rect x="1" y="18" width="1" height="1" className="path-fill" />
      <rect x="2" y="18" width="1" height="1" className="path-fill" />
      <rect x="3" y="18" width="1" height="1" className="path-fill" />
      <rect x="12" y="18" width="1" height="1" className="path-fill" />
      <rect x="13" y="18" width="1" height="1" className="path-fill" />
      <rect x="14" y="18" width="1" height="1" className="path-fill" />
      <rect x="15" y="18" width="1" height="1" className="path-fill" />
      <rect x="32" y="18" width="1" height="1" className="path-fill" />
      <rect x="33" y="18" width="1" height="1" className="path-fill" />
      <rect x="34" y="18" width="1" height="1" className="path-fill" />
      <rect x="35" y="18" width="1" height="1" className="path-fill" />
      <rect x="0" y="19" width="1" height="1" className="path-fill" />
      <rect x="1" y="19" width="1" height="1" className="path-fill" />
      <rect x="2" y="19" width="1" height="1" className="path-fill" />
      <rect x="3" y="19" width="1" height="1" className="path-fill" />
      <rect x="12" y="19" width="1" height="1" className="path-fill" />
      <rect x="13" y="19" width="1" height="1" className="path-fill" />
      <rect x="14" y="19" width="1" height="1" className="path-fill" />
      <rect x="15" y="19" width="1" height="1" className="path-fill" />
      <rect x="32" y="19" width="1" height="1" className="path-fill" />
      <rect x="33" y="19" width="1" height="1" className="path-fill" />
      <rect x="34" y="19" width="1" height="1" className="path-fill" />
      <rect x="35" y="19" width="1" height="1" className="path-fill" />
      <rect x="0" y="20" width="1" height="1" className="path-fill" />
      <rect x="1" y="20" width="1" height="1" className="path-fill" />
      <rect x="2" y="20" width="1" height="1" className="path-fill" />
      <rect x="3" y="20" width="1" height="1" className="path-fill" />
      <rect x="12" y="20" width="1" height="1" className="path-fill" />
      <rect x="13" y="20" width="1" height="1" className="path-fill" />
      <rect x="14" y="20" width="1" height="1" className="path-fill" />
      <rect x="15" y="20" width="1" height="1" className="path-fill" />
      <rect x="32" y="20" width="1" height="1" className="path-fill" />
      <rect x="33" y="20" width="1" height="1" className="path-fill" />
      <rect x="34" y="20" width="1" height="1" className="path-fill" />
      <rect x="35" y="20" width="1" height="1" className="path-fill" />
      <rect x="0" y="21" width="1" height="1" className="path-fill" />
      <rect x="1" y="21" width="1" height="1" className="path-fill" />
      <rect x="2" y="21" width="1" height="1" className="path-fill" />
      <rect x="3" y="21" width="1" height="1" className="path-fill" />
      <rect x="12" y="21" width="1" height="1" className="path-fill" />
      <rect x="13" y="21" width="1" height="1" className="path-fill" />
      <rect x="14" y="21" width="1" height="1" className="path-fill" />
      <rect x="15" y="21" width="1" height="1" className="path-fill" />
      <rect x="32" y="21" width="1" height="1" className="path-fill" />
      <rect x="33" y="21" width="1" height="1" className="path-fill" />
      <rect x="34" y="21" width="1" height="1" className="path-fill" />
      <rect x="35" y="21" width="1" height="1" className="path-fill" />
      <rect x="0" y="22" width="1" height="1" className="path-fill" />
      <rect x="1" y="22" width="1" height="1" className="path-fill" />
      <rect x="2" y="22" width="1" height="1" className="path-fill" />
      <rect x="3" y="22" width="1" height="1" className="path-fill" />
      <rect x="12" y="22" width="1" height="1" className="path-fill" />
      <rect x="13" y="22" width="1" height="1" className="path-fill" />
      <rect x="14" y="22" width="1" height="1" className="path-fill" />
      <rect x="15" y="22" width="1" height="1" className="path-fill" />
      <rect x="32" y="22" width="1" height="1" className="path-fill" />
      <rect x="33" y="22" width="1" height="1" className="path-fill" />
      <rect x="34" y="22" width="1" height="1" className="path-fill" />
      <rect x="35" y="22" width="1" height="1" className="path-fill" />
      <rect x="0" y="23" width="1" height="1" className="path-fill" />
      <rect x="1" y="23" width="1" height="1" className="path-fill" />
      <rect x="2" y="23" width="1" height="1" className="path-fill" />
      <rect x="3" y="23" width="1" height="1" className="path-fill" />
      <rect x="12" y="23" width="1" height="1" className="path-fill" />
      <rect x="13" y="23" width="1" height="1" className="path-fill" />
      <rect x="14" y="23" width="1" height="1" className="path-fill" />
      <rect x="15" y="23" width="1" height="1" className="path-fill" />
      <rect x="32" y="23" width="1" height="1" className="path-fill" />
      <rect x="33" y="23" width="1" height="1" className="path-fill" />
      <rect x="34" y="23" width="1" height="1" className="path-fill" />
      <rect x="35" y="23" width="1" height="1" className="path-fill" />
      <rect x="0" y="24" width="1" height="1" className="path-fill" />
      <rect x="1" y="24" width="1" height="1" className="path-fill" />
      <rect x="2" y="24" width="1" height="1" className="path-fill" />
      <rect x="3" y="24" width="1" height="1" className="path-fill" />
      <rect x="12" y="24" width="1" height="1" className="path-fill" />
      <rect x="13" y="24" width="1" height="1" className="path-fill" />
      <rect x="14" y="24" width="1" height="1" className="path-fill" />
      <rect x="15" y="24" width="1" height="1" className="path-fill" />
      <rect x="32" y="24" width="1" height="1" className="path-fill" />
      <rect x="33" y="24" width="1" height="1" className="path-fill" />
      <rect x="34" y="24" width="1" height="1" className="path-fill" />
      <rect x="35" y="24" width="1" height="1" className="path-fill" />
      <rect x="0" y="25" width="1" height="1" className="path-fill" />
      <rect x="1" y="25" width="1" height="1" className="path-fill" />
      <rect x="2" y="25" width="1" height="1" className="path-fill" />
      <rect x="3" y="25" width="1" height="1" className="path-fill" />
      <rect x="12" y="25" width="1" height="1" className="path-fill" />
      <rect x="13" y="25" width="1" height="1" className="path-fill" />
      <rect x="14" y="25" width="1" height="1" className="path-fill" />
      <rect x="15" y="25" width="1" height="1" className="path-fill" />
      <rect x="32" y="25" width="1" height="1" className="path-fill" />
      <rect x="33" y="25" width="1" height="1" className="path-fill" />
      <rect x="34" y="25" width="1" height="1" className="path-fill" />
      <rect x="35" y="25" width="1" height="1" className="path-fill" />
      <rect x="0" y="26" width="1" height="1" className="path-fill" />
      <rect x="1" y="26" width="1" height="1" className="path-fill" />
      <rect x="2" y="26" width="1" height="1" className="path-fill" />
      <rect x="3" y="26" width="1" height="1" className="path-fill" />
      <rect x="12" y="26" width="1" height="1" className="path-fill" />
      <rect x="13" y="26" width="1" height="1" className="path-fill" />
      <rect x="14" y="26" width="1" height="1" className="path-fill" />
      <rect x="15" y="26" width="1" height="1" className="path-fill" />
      <rect x="32" y="26" width="1" height="1" className="path-fill" />
      <rect x="33" y="26" width="1" height="1" className="path-fill" />
      <rect x="34" y="26" width="1" height="1" className="path-fill" />
      <rect x="35" y="26" width="1" height="1" className="path-fill" />
      <rect x="0" y="27" width="1" height="1" className="path-fill" />
      <rect x="1" y="27" width="1" height="1" className="path-fill" />
      <rect x="2" y="27" width="1" height="1" className="path-fill" />
      <rect x="3" y="27" width="1" height="1" className="path-fill" />
      <rect x="12" y="27" width="1" height="1" className="path-fill" />
      <rect x="13" y="27" width="1" height="1" className="path-fill" />
      <rect x="14" y="27" width="1" height="1" className="path-fill" />
      <rect x="15" y="27" width="1" height="1" className="path-fill" />
      <rect x="32" y="27" width="1" height="1" className="path-fill" />
      <rect x="33" y="27" width="1" height="1" className="path-fill" />
      <rect x="34" y="27" width="1" height="1" className="path-fill" />
      <rect x="35" y="27" width="1" height="1" className="path-fill" />
      <rect x="0" y="28" width="1" height="1" className="path-fill" />
      <rect x="1" y="28" width="1" height="1" className="path-fill" />
      <rect x="2" y="28" width="1" height="1" className="path-fill" />
      <rect x="3" y="28" width="1" height="1" className="path-fill" />
      <rect x="4" y="28" width="1" height="1" className="path-fill" />
      <rect x="5" y="28" width="1" height="1" className="path-fill" />
      <rect x="6" y="28" width="1" height="1" className="path-fill" />
      <rect x="7" y="28" width="1" height="1" className="path-fill" />
      <rect x="8" y="28" width="1" height="1" className="path-fill" />
      <rect x="9" y="28" width="1" height="1" className="path-fill" />
      <rect x="10" y="28" width="1" height="1" className="path-fill" />
      <rect x="11" y="28" width="1" height="1" className="path-fill" />
      <rect x="12" y="28" width="1" height="1" className="path-fill" />
      <rect x="13" y="28" width="1" height="1" className="path-fill" />
      <rect x="14" y="28" width="1" height="1" className="path-fill" />
      <rect x="15" y="28" width="1" height="1" className="path-fill" />
      <rect x="32" y="28" width="1" height="1" className="path-fill" />
      <rect x="33" y="28" width="1" height="1" className="path-fill" />
      <rect x="34" y="28" width="1" height="1" className="path-fill" />
      <rect x="35" y="28" width="1" height="1" className="path-fill" />
      <rect x="0" y="29" width="1" height="1" className="path-fill" />
      <rect x="1" y="29" width="1" height="1" className="path-fill" />
      <rect x="2" y="29" width="1" height="1" className="path-fill" />
      <rect x="3" y="29" width="1" height="1" className="path-fill" />
      <rect x="4" y="29" width="1" height="1" className="path-fill" />
      <rect x="5" y="29" width="1" height="1" className="path-fill" />
      <rect x="6" y="29" width="1" height="1" className="path-fill" />
      <rect x="7" y="29" width="1" height="1" className="path-fill" />
      <rect x="8" y="29" width="1" height="1" className="path-fill" />
      <rect x="9" y="29" width="1" height="1" className="path-fill" />
      <rect x="10" y="29" width="1" height="1" className="path-fill" />
      <rect x="11" y="29" width="1" height="1" className="path-fill" />
      <rect x="12" y="29" width="1" height="1" className="path-fill" />
      <rect x="13" y="29" width="1" height="1" className="path-fill" />
      <rect x="14" y="29" width="1" height="1" className="path-fill" />
      <rect x="15" y="29" width="1" height="1" className="path-fill" />
      <rect x="32" y="29" width="1" height="1" className="path-fill" />
      <rect x="33" y="29" width="1" height="1" className="path-fill" />
      <rect x="34" y="29" width="1" height="1" className="path-fill" />
      <rect x="35" y="29" width="1" height="1" className="path-fill" />
      <rect x="0" y="30" width="1" height="1" className="path-fill" />
      <rect x="1" y="30" width="1" height="1" className="path-fill" />
      <rect x="2" y="30" width="1" height="1" className="path-fill" />
      <rect x="3" y="30" width="1" height="1" className="path-fill" />
      <rect x="4" y="30" width="1" height="1" className="path-fill" />
      <rect x="5" y="30" width="1" height="1" className="path-fill" />
      <rect x="6" y="30" width="1" height="1" className="path-fill" />
      <rect x="7" y="30" width="1" height="1" className="path-fill" />
      <rect x="8" y="30" width="1" height="1" className="path-fill" />
      <rect x="9" y="30" width="1" height="1" className="path-fill" />
      <rect x="10" y="30" width="1" height="1" className="path-fill" />
      <rect x="11" y="30" width="1" height="1" className="path-fill" />
      <rect x="12" y="30" width="1" height="1" className="path-fill" />
      <rect x="13" y="30" width="1" height="1" className="path-fill" />
      <rect x="14" y="30" width="1" height="1" className="path-fill" />
      <rect x="15" y="30" width="1" height="1" className="path-fill" />
      <rect x="32" y="30" width="1" height="1" className="path-fill" />
      <rect x="33" y="30" width="1" height="1" className="path-fill" />
      <rect x="34" y="30" width="1" height="1" className="path-fill" />
      <rect x="35" y="30" width="1" height="1" className="path-fill" />
      <rect x="0" y="31" width="1" height="1" className="path-fill" />
      <rect x="1" y="31" width="1" height="1" className="path-fill" />
      <rect x="2" y="31" width="1" height="1" className="path-fill" />
      <rect x="3" y="31" width="1" height="1" className="path-fill" />
      <rect x="4" y="31" width="1" height="1" className="path-fill" />
      <rect x="5" y="31" width="1" height="1" className="path-fill" />
      <rect x="6" y="31" width="1" height="1" className="path-fill" />
      <rect x="7" y="31" width="1" height="1" className="path-fill" />
      <rect x="8" y="31" width="1" height="1" className="path-fill" />
      <rect x="9" y="31" width="1" height="1" className="path-fill" />
      <rect x="10" y="31" width="1" height="1" className="path-fill" />
      <rect x="11" y="31" width="1" height="1" className="path-fill" />
      <rect x="12" y="31" width="1" height="1" className="path-fill" />
      <rect x="13" y="31" width="1" height="1" className="path-fill" />
      <rect x="14" y="31" width="1" height="1" className="path-fill" />
      <rect x="15" y="31" width="1" height="1" className="path-fill" />
      <rect x="32" y="31" width="1" height="1" className="path-fill" />
      <rect x="33" y="31" width="1" height="1" className="path-fill" />
      <rect x="34" y="31" width="1" height="1" className="path-fill" />
      <rect x="35" y="31" width="1" height="1" className="path-fill" />
      <rect x="12" y="32" width="1" height="1" className="path-fill" />
      <rect x="13" y="32" width="1" height="1" className="path-fill" />
      <rect x="14" y="32" width="1" height="1" className="path-fill" />
      <rect x="15" y="32" width="1" height="1" className="path-fill" />
      <rect x="32" y="32" width="1" height="1" className="path-fill" />
      <rect x="33" y="32" width="1" height="1" className="path-fill" />
      <rect x="34" y="32" width="1" height="1" className="path-fill" />
      <rect x="35" y="32" width="1" height="1" className="path-fill" />
      <rect x="12" y="33" width="1" height="1" className="path-fill" />
      <rect x="13" y="33" width="1" height="1" className="path-fill" />
      <rect x="14" y="33" width="1" height="1" className="path-fill" />
      <rect x="15" y="33" width="1" height="1" className="path-fill" />
      <rect x="32" y="33" width="1" height="1" className="path-fill" />
      <rect x="33" y="33" width="1" height="1" className="path-fill" />
      <rect x="34" y="33" width="1" height="1" className="path-fill" />
      <rect x="35" y="33" width="1" height="1" className="path-fill" />
      <rect x="12" y="34" width="1" height="1" className="path-fill" />
      <rect x="13" y="34" width="1" height="1" className="path-fill" />
      <rect x="14" y="34" width="1" height="1" className="path-fill" />
      <rect x="15" y="34" width="1" height="1" className="path-fill" />
      <rect x="32" y="34" width="1" height="1" className="path-fill" />
      <rect x="33" y="34" width="1" height="1" className="path-fill" />
      <rect x="34" y="34" width="1" height="1" className="path-fill" />
      <rect x="35" y="34" width="1" height="1" className="path-fill" />
      <rect x="12" y="35" width="1" height="1" className="path-fill" />
      <rect x="13" y="35" width="1" height="1" className="path-fill" />
      <rect x="14" y="35" width="1" height="1" className="path-fill" />
      <rect x="15" y="35" width="1" height="1" className="path-fill" />
      <rect x="32" y="35" width="1" height="1" className="path-fill" />
      <rect x="33" y="35" width="1" height="1" className="path-fill" />
      <rect x="34" y="35" width="1" height="1" className="path-fill" />
      <rect x="35" y="35" width="1" height="1" className="path-fill" />
      <rect x="12" y="36" width="1" height="1" className="path-fill" />
      <rect x="13" y="36" width="1" height="1" className="path-fill" />
      <rect x="14" y="36" width="1" height="1" className="path-fill" />
      <rect x="15" y="36" width="1" height="1" className="path-fill" />
      <rect x="16" y="36" width="1" height="1" className="path-fill" />
      <rect x="17" y="36" width="1" height="1" className="path-fill" />
      <rect x="18" y="36" width="1" height="1" className="path-fill" />
      <rect x="19" y="36" width="1" height="1" className="path-fill" />
      <rect x="20" y="36" width="1" height="1" className="path-fill" />
      <rect x="21" y="36" width="1" height="1" className="path-fill" />
      <rect x="22" y="36" width="1" height="1" className="path-fill" />
      <rect x="23" y="36" width="1" height="1" className="path-fill" />
      <rect x="24" y="36" width="1" height="1" className="path-fill" />
      <rect x="25" y="36" width="1" height="1" className="path-fill" />
      <rect x="26" y="36" width="1" height="1" className="path-fill" />
      <rect x="27" y="36" width="1" height="1" className="path-fill" />
      <rect x="28" y="36" width="1" height="1" className="path-fill" />
      <rect x="29" y="36" width="1" height="1" className="path-fill" />
      <rect x="30" y="36" width="1" height="1" className="path-fill" />
      <rect x="31" y="36" width="1" height="1" className="path-fill" />
      <rect x="32" y="36" width="1" height="1" className="path-fill" />
      <rect x="33" y="36" width="1" height="1" className="path-fill" />
      <rect x="34" y="36" width="1" height="1" className="path-fill" />
      <rect x="35" y="36" width="1" height="1" className="path-fill" />
      <rect x="12" y="37" width="1" height="1" className="path-fill" />
      <rect x="13" y="37" width="1" height="1" className="path-fill" />
      <rect x="14" y="37" width="1" height="1" className="path-fill" />
      <rect x="15" y="37" width="1" height="1" className="path-fill" />
      <rect x="16" y="37" width="1" height="1" className="path-fill" />
      <rect x="17" y="37" width="1" height="1" className="path-fill" />
      <rect x="18" y="37" width="1" height="1" className="path-fill" />
      <rect x="19" y="37" width="1" height="1" className="path-fill" />
      <rect x="20" y="37" width="1" height="1" className="path-fill" />
      <rect x="21" y="37" width="1" height="1" className="path-fill" />
      <rect x="22" y="37" width="1" height="1" className="path-fill" />
      <rect x="23" y="37" width="1" height="1" className="path-fill" />
      <rect x="24" y="37" width="1" height="1" className="path-fill" />
      <rect x="25" y="37" width="1" height="1" className="path-fill" />
      <rect x="26" y="37" width="1" height="1" className="path-fill" />
      <rect x="27" y="37" width="1" height="1" className="path-fill" />
      <rect x="28" y="37" width="1" height="1" className="path-fill" />
      <rect x="29" y="37" width="1" height="1" className="path-fill" />
      <rect x="30" y="37" width="1" height="1" className="path-fill" />
      <rect x="31" y="37" width="1" height="1" className="path-fill" />
      <rect x="32" y="37" width="1" height="1" className="path-fill" />
      <rect x="33" y="37" width="1" height="1" className="path-fill" />
      <rect x="34" y="37" width="1" height="1" className="path-fill" />
      <rect x="35" y="37" width="1" height="1" className="path-fill" />
      <rect x="12" y="38" width="1" height="1" className="path-fill" />
      <rect x="13" y="38" width="1" height="1" className="path-fill" />
      <rect x="14" y="38" width="1" height="1" className="path-fill" />
      <rect x="15" y="38" width="1" height="1" className="path-fill" />
      <rect x="16" y="38" width="1" height="1" className="path-fill" />
      <rect x="17" y="38" width="1" height="1" className="path-fill" />
      <rect x="18" y="38" width="1" height="1" className="path-fill" />
      <rect x="19" y="38" width="1" height="1" className="path-fill" />
      <rect x="20" y="38" width="1" height="1" className="path-fill" />
      <rect x="21" y="38" width="1" height="1" className="path-fill" />
      <rect x="22" y="38" width="1" height="1" className="path-fill" />
      <rect x="23" y="38" width="1" height="1" className="path-fill" />
      <rect x="24" y="38" width="1" height="1" className="path-fill" />
      <rect x="25" y="38" width="1" height="1" className="path-fill" />
      <rect x="26" y="38" width="1" height="1" className="path-fill" />
      <rect x="27" y="38" width="1" height="1" className="path-fill" />
      <rect x="28" y="38" width="1" height="1" className="path-fill" />
      <rect x="29" y="38" width="1" height="1" className="path-fill" />
      <rect x="30" y="38" width="1" height="1" className="path-fill" />
      <rect x="31" y="38" width="1" height="1" className="path-fill" />
      <rect x="32" y="38" width="1" height="1" className="path-fill" />
      <rect x="33" y="38" width="1" height="1" className="path-fill" />
      <rect x="34" y="38" width="1" height="1" className="path-fill" />
      <rect x="35" y="38" width="1" height="1" className="path-fill" />
      <rect x="12" y="39" width="1" height="1" className="path-fill" />
      <rect x="13" y="39" width="1" height="1" className="path-fill" />
      <rect x="14" y="39" width="1" height="1" className="path-fill" />
      <rect x="15" y="39" width="1" height="1" className="path-fill" />
      <rect x="16" y="39" width="1" height="1" className="path-fill" />
      <rect x="17" y="39" width="1" height="1" className="path-fill" />
      <rect x="18" y="39" width="1" height="1" className="path-fill" />
      <rect x="19" y="39" width="1" height="1" className="path-fill" />
      <rect x="20" y="39" width="1" height="1" className="path-fill" />
      <rect x="21" y="39" width="1" height="1" className="path-fill" />
      <rect x="22" y="39" width="1" height="1" className="path-fill" />
      <rect x="23" y="39" width="1" height="1" className="path-fill" />
      <rect x="24" y="39" width="1" height="1" className="path-fill" />
      <rect x="25" y="39" width="1" height="1" className="path-fill" />
      <rect x="26" y="39" width="1" height="1" className="path-fill" />
      <rect x="27" y="39" width="1" height="1" className="path-fill" />
      <rect x="28" y="39" width="1" height="1" className="path-fill" />
      <rect x="29" y="39" width="1" height="1" className="path-fill" />
      <rect x="30" y="39" width="1" height="1" className="path-fill" />
      <rect x="31" y="39" width="1" height="1" className="path-fill" />
      <rect x="32" y="39" width="1" height="1" className="path-fill" />
      <rect x="33" y="39" width="1" height="1" className="path-fill" />
      <rect x="34" y="39" width="1" height="1" className="path-fill" />
      <rect x="35" y="39" width="1" height="1" className="path-fill" />
    </svg>
  );
};
export default CopySvg;
